spring:
  application:
    name: talent-service
  
  datasource:
    url: jdbc:postgresql://localhost:5432/ags_talent
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      
  cloud:
    discovery:
      enabled: true

server:
  port: 8081
  servlet:
    context-path: /api/talent

mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  type-aliases-package: com.ags.talent.entity
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30

logging:
  level:
    com.ags.talent: DEBUG
    org.springframework: INFO
    com.zaxxer.hikari: INFO
    org.mybatis: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always 