spring:
  config:
    import: classpath:config.yml

  profiles:
    active: local

  application:
    name: common

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/oco?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&connectTimeout=30
    username: com_dev
    password: qwer1234!
    hikari:
      auto-commit: false
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000
      validation-timeout: 5000
      connection-test-query: SELECT 1

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: oco
        jdbc:
          time_zone: UTC
          batch_size: 100
          order_inserts: true
          order_updates: true
          batch_versioned_data: true
        connection:
          provider_disables_autocommit: true
    open-in-view: false

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.skcc.ra.common.domain
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30

springdoc:
  api-docs:
    path: "/com/common/docs" # 접속 path 설정
    #enabled: false
  swagger-ui:
    path: "/com/common/swagger-ui" # 접속 path 설정
    display-request-duration: true  # try it out 을 했을 때 request duration 을 추가로 찍어줌
    #enabled: false
  cache:
    disabled: true # swagger cache 설정

app:
  secret-key: 6fl4oppus58ggi3uxnckbw1s13048caf
---

spring:
  config:
    activate:
      on-profile: local-env

  data:
    redis:
      database: 0
      host: localhost
      port: 6379
      password: "changeme"
      timeout: 30000
      lettuce:
        pool:
          maxTotal: 8
          maxWaitMillis: 10000
          maxIdle: 8
          minIdle: 0

feign:
  account-service.url: http://localhost:9101
  authorization-service.url: http://localhost:9101

server:
  port: 9100
  servlet:
       encoding:
         charset: UTF-8
         force: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.zaxxer.hikari: DEBUG
    org.postgresql: DEBUG
    org.springframework.jdbc.core: TRACE
---

spring:
  config:
    activate:
      on-profile: dev-env

---

spring:
  config:
    activate:
      on-profile: stg-env
---

spring:
  config:
    activate:
      on-profile: prd-env